export default [
  [{
    fn: 'letter',
    en: '`',
    enShift: '~',
    ru: 'ё',
    ruShift: 'Ё',
  },
  {
    fn: 'letter',
    en: '1',
    enShift: '!',
    ru: '1',
    ruShift: '!',
  },
  {
    fn: 'letter',
    en: '2',
    enShift: '@',
    ru: '2',
    ruShift: '&quot;',
  },
  {
    fn: 'letter',
    en: '3',
    enShift: '#',
    ru: '3',
    ruShift: '№',
  },
  {
    fn: 'letter',
    en: '4',
    enShift: '$',
    ru: '4',
    ruShift: ';',
  },
  {
    fn: 'letter',
    en: '5',
    enShift: '%',
    ru: '5',
    ruShift: '%',
  },
  {
    fn: 'letter',
    en: '6',
    enShift: '^',
    ru: '6',
    ruShift: ':',
  },
  {
    fn: 'letter',
    en: '7',
    enShift: '&',
    ru: '7',
    ruShift: '?',
  },
  {
    fn: 'letter',
    en: '8',
    enShift: '*',
    ru: '8',
    ruShift: '*',
  },
  {
    fn: 'letter',
    en: '9',
    enShift: '(',
    ru: '9',
    ruShift: '(',
  },
  {
    fn: 'letter',
    en: '0',
    enShift: ')',
    ru: '0',
    ruShift: ')',
  },
  {
    fn: 'letter',
    en: '-',
    enShift: '_',
    ru: '-',
    ruShift: '_',
  },
  {
    fn: 'letter',
    en: '=',
    enShift: '+',
    ru: '=',
    ruShift: '+',
  },
  {
    fn: 'backspace',
    en: 'Backspace',
    enShift: 'Backspace',
    ru: 'Backspace',
    ruShift: 'Backspace',
  }],
  [
    {
      fn: 'tab',
      en: 'Tab',
      enShift: 'Tab',
      ru: 'Tab',
      ruShift: 'Tab',
    },
    {
      fn: 'letter',
      en: 'q',
      enShift: 'Q',
      ru: 'й',
      ruShift: 'Й',
    },
    {
      fn: 'letter',
      en: 'w',
      enShift: 'W',
      ru: 'ц',
      ruShift: 'Ц',
    },
    {
      fn: 'letter',
      en: 'e',
      enShift: 'E',
      ru: 'у',
      ruShift: 'У',
    },
    {
      fn: 'letter',
      en: 'r',
      enShift: 'R',
      ru: 'к',
      ruShift: 'К',
    },
    {
      fn: 'letter',
      en: 't',
      enShift: 'T',
      ru: 'е',
      ruShift: 'Е',
    },
    {
      fn: 'letter',
      en: 'y',
      enShift: 'Y',
      ru: 'н',
      ruShift: 'Н',
    },
    {
      fn: 'letter',
      en: 'u',
      enShift: 'U',
      ru: 'г',
      ruShift: 'Г',
    },
    {
      fn: 'letter',
      en: 'i',
      enShift: 'I',
      ru: 'ш',
      ruShift: 'Ш',
    },
    {
      fn: 'letter',
      en: 'o',
      enShift: 'O',
      ru: 'щ',
      ruShift: 'Щ',
    },
    {
      fn: 'letter',
      en: 'p',
      enShift: 'P',
      ru: 'з',
      ruShift: 'З',
    },
    {
      fn: 'letter',
      en: '[',
      enShift: '{',
      ru: 'х',
      ruShift: 'Х',
    },
    {
      fn: 'letter',
      en: ']',
      enShift: '}',
      ru: 'ъ',
      ruShift: 'Ъ',
    },
    {
      fn: 'del',
      en: 'Del',
      enShift: 'Del',
      ru: 'Del',
      ruShift: 'Del',
    },
  ],
  [
    {
      fn: 'capsLock',
      en: 'Caps Lock',
      enShift: 'Caps Lock',
      ru: 'Caps Lock',
      ruShift: 'Caps Lock',
    },
    {
      fn: 'letter',
      en: 'a',
      enShift: 'A',
      ru: 'ф',
      ruShift: 'Ф',
    },
    {
      fn: 'letter',
      en: 's',
      enShift: 'S',
      ru: 'ы',
      ruShift: 'Ы',
    },
    {
      fn: 'letter',
      en: 'd',
      enShift: 'D',
      ru: 'в',
      ruShift: 'В',
    },
    {
      fn: 'letter',
      en: 'f',
      enShift: 'F',
      ru: 'а',
      ruShift: 'А',
    },
    {
      fn: 'letter',
      en: 'g',
      enShift: 'G',
      ru: 'п',
      ruShift: 'П',
    },
    {
      fn: 'letter',
      en: 'h',
      enShift: 'H',
      ru: 'р',
      ruShift: 'Р',
    },
    {
      fn: 'letter',
      en: 'j',
      enShift: 'J',
      ru: 'о',
      ruShift: 'О',
    },
    {
      fn: 'letter',
      en: 'k',
      enShift: 'K',
      ru: 'л',
      ruShift: 'Л',
    },
    {
      fn: 'letter',
      en: 'l',
      enShift: 'L',
      ru: 'д',
      ruShift: 'Д',
    },
    {
      fn: 'letter',
      en: ';',
      enShift: ':',
      ru: 'ж',
      ruShift: 'Ж',
    },
    {
      fn: 'letter',
      en: '\'',
      enShift: '&quot;',
      ru: 'э',
      ruShift: 'Э',
    },
    {
      fn: 'enter',
      en: 'Enter',
      enShift: 'Enter',
      ru: 'Enter',
      ruShift: 'Enter',
    },
  ],
  [
    {
      fn: 'leftShift',
      en: 'Shift',
      enShift: 'Shift',
      ru: 'Shift',
      ruShift: 'Shift',
    },
    {
      fn: 'letter',
      en: 'z',
      enShift: 'Z',
      ru: 'я',
      ruShift: 'Я',
    },
    {
      fn: 'letter',
      en: 'x',
      enShift: 'X',
      ru: 'ч',
      ruShift: 'Ч',
    },
    {
      fn: 'letter',
      en: 'c',
      enShift: 'C',
      ru: 'с',
      ruShift: 'С',
    },
    {
      fn: 'letter',
      en: 'v',
      enShift: 'V',
      ru: 'м',
      ruShift: 'М',
    },
    {
      fn: 'letter',
      en: 'b',
      enShift: 'B',
      ru: 'и',
      ruShift: 'И',
    },
    {
      fn: 'letter',
      en: 'n',
      enShift: 'N',
      ru: 'т',
      ruShift: 'Т',
    },
    {
      fn: 'letter',
      en: 'm',
      enShift: 'M',
      ru: 'ь',
      ruShift: 'Ь',
    },
    {
      fn: 'letter',
      en: ',',
      enShift: '<',
      ru: 'б',
      ruShift: 'Б',
    },
    {
      fn: 'letter',
      en: '.',
      enShift: '>',
      ru: 'ю',
      ruShift: 'Ю',
    },
    {
      fn: 'letter',
      en: '/',
      enShift: '?',
      ru: '.',
      ruShift: ',',
    },
    {
      fn: 'arrowUp',
      en: '▲',
      enShift: '▲',
      ru: '▲',
      ruShift: '▲',
    },
    {
      fn: 'rightShift',
      en: 'Shift',
      enShift: 'Shift',
      ru: 'Shift',
      ruShift: 'Shift',
    },
  ],
  [
    {
      fn: 'leftCtrl',
      en: 'Ctrl',
      enShift: 'Ctrl',
      ru: 'Ctrl',
      ruShift: 'Ctrl',
    },
    {
      fn: 'win',
      en: 'Win',
      enShift: 'Win',
      ru: 'Win',
      ruShift: 'Win',
    },
    {
      fn: 'leftAlt',
      en: 'Alt',
      enShift: 'Alt',
      ru: 'Alt',
      ruShift: 'Alt',
    },
    {
      fn: 'space',
      en: '&#32;',
      enShift: '&#32;',
      ru: '&#32;',
      ruShift: '&#32;',
    },
    {
      fn: 'rightAlt',
      en: 'Alt',
      enShift: 'Alt',
      ru: 'Alt',
      ruShift: 'Alt',
    },
    {
      fn: 'arrowLeft',
      en: '◄',
      enShift: '◄',
      ru: '◄',
      ruShift: '◄',
    },
    {
      fn: 'arrowDown',
      en: '▼',
      enShift: '▼',
      ru: '▼',
      ruShift: '▼',
    },
    {
      fn: 'arrowRight',
      en: '►',
      enShift: '►',
      ru: '►',
      ruShift: '►',
    },
    {
      fn: 'rightCtrl',
      en: 'Ctrl',
      enShift: 'Ctrl',
      ru: 'Ctrl',
      ruShift: 'Ctrl',
    },
  ],
];
